"use client"
import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import {
  QueryClient,
  QueryClientProvider,
  
} from '@tanstack/react-query'

const queryClient = new QueryClient()// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',

export default function RootLayout({ children }) {
  return (

    <html lang="en">
          <QueryClientProvider client={queryClient}>      <body className={inter.className}>

        <Navbar />

        {children}

        </body>
        </QueryClientProvider>

      
    </html>

  )
}
